apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-api-server
  namespace: airflow
  labels:
    app: airflow-api-server
    component: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-api-server
      component: apiserver
  template:
    metadata:
      labels:
        app: airflow-api-server
        component: apiserver
    spec:
      volumes:
        {{- include "airflow.dags.volume" . | nindent 8 }}
      securityContext:
        fsGroup: 50000   # REQUIRED for Airflow file permissions

      containers:
        - name: airflow-apiserver
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          command:
            - bash
            - -c
            - "exec airflow api-server"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
                  {{- include "airflow.dags.volumeMount" . | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10