apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow-scheduler
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
        component: scheduler
    spec:
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      volumes:
        {{- include "airflow.dags.volume" . | nindent 8 }}
        {{- include "airflow.logs.volume" . | nindent 8 }}
      containers:
        - name: scheduler
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          command:
            - bash
            - -c
            - "exec airflow scheduler"
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
                  {{- include "airflow.dags.volumeMount" . | nindent 12 }}
                  {{- include "airflow.logs.volumeMount" . | nindent 12 }}