apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: airflow
  labels:
    app: airflow-triggerer
    component: triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
      component: triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
        component: triggerer
    spec:
      containers:
        - name: triggerer
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          command:
            - bash
            - -c
            - "exec airflow triggerer"
          envFrom:
            - configMapRef:
                name: airflow-config